"""Character sprites: 32x48 frames, 4 directions, 4-frame walk cycle.

A character = body template (down/side/up) coloured through a per-character
key + hair overlay + optional hat + optional extras. Walk frames swap the leg
block. Every NPC gets the full set so any of them can walk later.
"""
import json
import os
from common import Canvas, PAL, shade, preview, ASSETS

FW, FH = 32, 48

# --- body templates -------------------------------------------------------
# o outline, s skin, S skin shadow, c coat, C coat shadow, l lapel, w shirt,
# v vest, p trousers, P trouser shadow, b boot, B boot shine, n cravat
BODY_DOWN = """
................................
................................
................................
................................
............oooooooo............
...........osssssssso...........
..........ossssssssssso.........
..........ossssssssssso.........
..........osssssssssssso........
..........osssssssssssso........
..........osssssssssssso........
..........osssssssssssso........
..........oSsssssssssSso........
..........oSsssssssssSso........
...........oSssssssssSo.........
...........oSSsssssSSo..........
............oSSSSSSSo...........
.............oSSSSSo............
............ooSSSSSoo...........
..........oonnSSSSSnnoo.........
.........occlnnnnnnnlcco........
........occclwnnnnnwlccco.......
........occclwwvvvwwlccco.......
.......ocCcclwvvvvvwlccCco......
.......ocCccclvvvvvlcccCco......
.......ocCcccclvvvlccccCco......
.......ocCccccclvlcccccCco......
.......ocCccccccccccccCCco......
.......oCCcccccccccccccCCo......
.......oCSccccccccccccSCCo......
.......oSSocccccccccccoSSo......
.......oSSoCcccccccccCoSSo......
........oo.oCcccccccCo.oo.......
...........oCcCcccCcCo..........
...........oCCcCCCcCCo..........
............oPpPPPpPo...........
............oPpPoPpPo...........
............oPpPoPpPo...........
............oPpPoPpPo...........
............oPpPoPpPo...........
............oPpPoPpPo...........
............oPpPoPpPo...........
............obbboobbo...........
............oBbboBbbo...........
............obbboobbo...........
............oooo.ooo............
................................
................................
"""

LEGS_DOWN = {
    "stand": """
............oPpPPPpPo...........
............oPpPoPpPo...........
............oPpPoPpPo...........
............oPpPoPpPo...........
............oPpPoPpPo...........
............oPpPoPpPo...........
............oPpPoPpPo...........
............obbboobbo...........
............oBbboBbbo...........
............obbboobbo...........
............oooo.ooo............
................................
""",
    "l": """
............oPpPPPpPo...........
............oPpPoPpPo...........
...........oPpPooPpPo...........
...........oPpPo.oPpPo..........
...........oPpPo.oPpPo..........
...........oPpPo..oPpo..........
...........obbbo..oPPo..........
...........oBbbo..obbo..........
...........obbbo..oBbo..........
............ooo...obbo..........
..................ooo...........
................................
""",
    "r": """
............oPpPPPpPo...........
............oPpPoPpPo...........
............oPpPooPpPo..........
...........oPpPo.oPpPo..........
...........oPpPo.oPpPo..........
...........oPpo..oPpPo..........
...........oPPo..obbbo..........
...........obbo..oBbbo..........
...........oBbo..obbbo..........
...........obbo...ooo...........
............ooo.................
................................
""",
}

BODY_SIDE = """
................................
................................
................................
................................
.............ooooooo............
............osssssssso..........
...........osssssssssso.........
...........ossssssssssso........
...........ossssssssssso........
...........ossssssssssso........
...........ossssssssssso........
...........ossssssssssso........
...........oSsssssssssso........
...........oSsssssssssso........
............oSsssssssso.........
............oSSsssssSo..........
.............oSSSSSSo...........
..............oSSSSo............
..............oSSSSo............
.............oonSSSoo...........
............occnnnncco..........
...........occcnnnnccco.........
...........occccwwcccco.........
...........occccwvcccco.........
...........oCccccvcccco.........
...........oCccccvcccco.........
...........oCcccccccccSo........
...........oCcccccccccSo........
...........oCcccccccccSo........
...........oCcccccccccSo........
...........oCccccccccccSo.......
...........oCccccccccccoo.......
...........oCcccccccccco........
...........oCcccccccccco........
............oCcccccccco.........
............oPPPpppPPo..........
............oPPPpppPPo..........
............oPPPpppPPo..........
............oPPPpppPPo..........
............oPPPpppPPo..........
............oPPPpppPPo..........
............oPPPpppPPo..........
............obbbbbbbbo..........
............oBbbbbbbbo..........
............obbbbbbbbbo.........
............oooooooooo..........
................................
................................
"""

LEGS_SIDE = {
    "stand": """
............oPPPpppPPo..........
............oPPPpppPPo..........
............oPPPpppPPo..........
............oPPPpppPPo..........
............oPPPpppPPo..........
............oPPPpppPPo..........
............oPPPpppPPo..........
............obbbbbbbbo..........
............oBbbbbbbbo..........
............obbbbbbbbbo.........
............oooooooooo..........
................................
""",
    "l": """
............oPPPpppPPo..........
............oPPPpppPPo..........
...........oPPPpooPPPo..........
..........oPPPpo.oPPPo..........
.........oPPPpo..oPPPo..........
.........oPPPo...oPPPo..........
........oPPPo....oPPPo..........
........obbbo....obbbo..........
........oBbbo....oBbbo..........
........obbbbo...obbbbo.........
........oooooo...oooooo.........
................................
""",
    "r": """
............oPPPpppPPo..........
............oPPPpppPPo..........
...........oPPPpooPPPo..........
...........oPPPo..oPPPo.........
...........oPPPo...oPPPo........
...........oPPPo....oPPPo.......
...........oPPPo....oPPPo.......
...........obbbo....obbbo.......
...........oBbbo....oBbbo.......
...........obbbbo...obbbbo......
...........oooooo...oooooo......
................................
""",
}

BODY_UP = """
................................
................................
................................
................................
............oooooooo............
...........osssssssso...........
..........ossssssssssso.........
..........ossssssssssso.........
..........osssssssssssso........
..........osssssssssssso........
..........osssssssssssso........
..........osssssssssssso........
..........osssssssssssso........
..........osssssssssssso........
...........ossssssssssso........
...........oSSssssssSSo.........
............oSSSSSSSSo..........
.............oSSSSSSo...........
............ooSSSSSSoo..........
..........ooccSSSSSSccoo........
.........occccccccccccco........
........occccccccccccccco.......
........occccccccccccccco.......
.......ocCcccccccccccccCco......
.......ocCcccccccccccccCco......
.......ocCcccccccccccccCco......
.......ocCcccccccccccccCco......
.......ocCcccccccccccccCco......
.......oCCcccccccccccccCCo......
.......oCSccccccccccccSCCo......
.......oSSocccccccccccoSSo......
.......oSSoCcccccccccCoSSo......
........oo.oCcccccccCo.oo.......
...........oCcccccccCo..........
...........oCCcccccCCo..........
............oPpPPPpPo...........
............oPpPoPpPo...........
............oPpPoPpPo...........
............oPpPoPpPo...........
............oPpPoPpPo...........
............oPpPoPpPo...........
............oPpPoPpPo...........
............obbboobbo...........
............obbboobbo...........
............obbboobbo...........
............oooo.ooo............
................................
................................
"""

# --- hair overlays (h hair, H hair shadow, o outline) -----------------------
HAIR = {
    "swept_up": {   # Jackson: tall, brushed up and back
        "down": """
...........hhhhhhhhhh...........
..........hhhhhhhhhhhh..........
.........hhhhhhhhhhhhhh.........
.........hhhhhhhhhhhhhhh........
..........HhhhhhhhhhhhH.........
..........HHhh......hhH.........
..........HH..........H.........
""",
        "side": """
..........hhhhhhhhhhh...........
.........hhhhhhhhhhhhh..........
........hhhhhhhhhhhhhhh.........
........Hhhhhhhhhhhhhhh.........
.........HhhhhhhhhhhhhH.........
..........HHhhhhhh..HHH.........
...........HHHHhhh..............
...............HHh..............
""",
        "up": """
...........hhhhhhhhhh...........
..........hhhhhhhhhhhh..........
.........hhhhhhhhhhhhhh.........
.........hhhhhhhhhhhhhhh........
..........hhhhhhhhhhhhh.........
..........Hhhhhhhhhhhhh.........
..........HhhhhhhhhhhhH.........
..........HHhhhhhhhhhHH.........
...........HHhhhhhhhHH..........
............HHHHHHHHH...........
""",
    },
    "brushed_back": {   # Calhoun: dense, straight back
        "down": """
................................
..........hhhhhhhhhhhh..........
.........hhhhhhhhhhhhhh.........
.........hhhhhhhhhhhhhhh........
..........HhhhhhhhhhhhH.........
..........HH..........H.........
""",
        "side": """
................................
.........hhhhhhhhhhhhhh.........
........hhhhhhhhhhhhhhh.........
........Hhhhhhhhhhhhhhh.........
.........HHhhhhhhhhhhhH.........
..........HH.....HhhhH..........
.................HHhh...........
""",
        "up": """
................................
..........hhhhhhhhhhhh..........
.........hhhhhhhhhhhhhh.........
.........hhhhhhhhhhhhhhh........
..........hhhhhhhhhhhhh.........
..........Hhhhhhhhhhhhh.........
..........HhhhhhhhhhhhH.........
..........HHhhhhhhhhhHH.........
...........HHhhhhhhhHH..........
""",
    },
    "receding": {   # Clay: high forehead, hair at the sides
        "down": """
................................
...........hhhhhhhhh............
..........hhhhhhhhhhhh..........
..........hhh......hhhh.........
..........Hh........hhH.........
..........Hh.........hH.........
..........H...........H.........
""",
        "side": """
................................
...........hhhhhhhhhhh..........
..........hhhhhhhhhhhhh.........
..........hhh.....hhhhh.........
..........Hh.......hhhH.........
...........H.......HhhH.........
....................HH..........
""",
        "up": """
................................
...........hhhhhhhhh............
..........hhhhhhhhhhhh..........
..........hhhhhhhhhhhhh.........
..........Hhhhhhhhhhhhh.........
..........HhhhhhhhhhhhH.........
..........HHhhhhhhhhhHH.........
...........HHhhhhhhhHH..........
""",
    },
    "curly": {   # Biddle
        "down": """
...........hhhh.hhhhh...........
..........hhhhhhhhhhhh..........
.........hhhhhhhhhhhhhh.........
.........hhhhhhhhhhhhhhh........
.........HhhhhhhhhhhhhhH........
.........HHhhhHHHHhhhhH.........
..........HhH......HhH..........
..........HH........HH..........
""",
        "side": """
...........hhhhhhhhhh...........
.........hhhhhhhhhhhhh..........
........hhhhhhhhhhhhhhh.........
........hhhhhhhhhhhhhhh.........
........HhhhhhhhhhhhhhH.........
........HHhhhH.HHhhhhH..........
.........HhH......HhhH..........
.........HH........HH...........
""",
        "up": """
...........hhhh.hhhhh...........
..........hhhhhhhhhhhh..........
.........hhhhhhhhhhhhhh.........
.........hhhhhhhhhhhhhhh........
.........hhhhhhhhhhhhhhh........
.........HhhhhhhhhhhhhhH........
.........HhhhhhhhhhhhhhH........
..........HhhhhhhhhhhhH.........
..........HHhhhhhhhhhHH.........
...........HHHhhhhhHHH..........
""",
    },
    "parted": {   # Ross: flat, side-parted
        "down": """
................................
..........hhhhhhhhhhhh..........
.........hhhhhhhhhhhhhh.........
.........hhhhhhHhhhhhhhh........
..........HhhhH..hhhhhH.........
..........HHH.......hhH.........
.....................HH.........
""",
        "side": """
................................
..........hhhhhhhhhhhh..........
.........hhhhhhhhhhhhhh.........
.........hhhhhhhhhhhhhh.........
..........HHhhhhhhhhhhH.........
............HHHHHhhhhH..........
.................HHhh...........
""",
        "up": """
................................
..........hhhhhhhhhhhh..........
.........hhhhhhhhhhhhhh.........
.........hhhhhhhhhhhhhhh........
..........hhhhhhhhhhhhh.........
..........Hhhhhhhhhhhhh.........
..........HhhhhhhhhhhhH.........
..........HHhhhhhhhhhHH.........
...........HHhhhhhhhHH..........
""",
    },
    "thin_messy": {   # Gregory
        "down": """
................................
...........h.hhhhh.h............
..........hhhhhhhhhhhh..........
..........hhh..hh...hhh.........
..........Hh.........hH.........
..........H...........H.........
""",
        "side": """
................................
...........h.hhhhhh.h...........
..........hhhhhhhhhhhh..........
..........hhh....hhhhh..........
..........Hh......hhhH..........
...........H.......HH...........
""",
        "up": """
................................
...........h.hhhhh.h............
..........hhhhhhhhhhhh..........
..........hhhhhhhhhhhhh.........
..........HhhhhhhhhhhhH.........
..........HHhhhhhhhhhHH.........
...........HHhhhhhhhHH..........
""",
    },
    "wild": {   # Lawrence
        "down": """
..........h.hhh.hhh.hh..........
.........hhhhhhhhhhhhhh.........
.........hhhhhhhhhhhhhhh........
........hhhhhhhhhhhhhhhh........
.........HhhhhH.HhhhhhhH........
.........HHhhH...HhhhhH.........
..........HH......HhhH..........
...................HH...........
""",
        "side": """
..........h.hhh.hhhh.h..........
........hhhhhhhhhhhhhh..........
.......hhhhhhhhhhhhhhhh.........
.......hhhhhhhhhhhhhhhh.........
........HhhhhhHhhhhhhhH.........
........HHhhH..HHhhhhhH.........
.........HH......HhhhH..........
..................HHH...........
""",
        "up": """
..........h.hhh.hhh.hh..........
.........hhhhhhhhhhhhhh.........
.........hhhhhhhhhhhhhhh........
........hhhhhhhhhhhhhhhh........
.........hhhhhhhhhhhhhhh........
.........HhhhhhhhhhhhhhH........
.........HhhhhhhhhhhhhhH........
..........HHhhhhhhhhhHH.........
...........HHhhhhhhhHH..........
""",
    },
    "bald_whiskers": {   # magistrate
        "down": """
................................
................................
................................
................................
................................
..........hh..........hh........
..........hhh........hhh........
..........hhh........hhh........
..........hhhh......hhhh........
..........Hhhh......hhhH........
...........HhH......HhH.........
""",
        "side": """
................................
................................
................................
................................
................................
...........hh...................
..........hhh...................
..........hhhh..................
..........hhhhh.................
..........Hhhhh.................
...........HhhH.................
""",
        "up": """
................................
................................
................................
................................
................................
..........hh..........hh........
..........hhh........hhh........
..........hhhh......hhhh........
..........Hhhh......hhhH........
...........HhH......HhH.........
""",
    },
    "short": {   # generic
        "down": """
................................
..........hhhhhhhhhhhh..........
.........hhhhhhhhhhhhhh.........
.........hhhhhhhhhhhhhhh........
..........Hhh.......hhH.........
..........H...........H.........
""",
        "side": """
................................
..........hhhhhhhhhhhh..........
.........hhhhhhhhhhhhhh.........
.........hhhhhhhhhhhhhh.........
..........HHh......hhhH.........
....................HH..........
""",
        "up": """
................................
..........hhhhhhhhhhhh..........
.........hhhhhhhhhhhhhh.........
.........hhhhhhhhhhhhhhh........
..........hhhhhhhhhhhhh.........
..........HhhhhhhhhhhhH.........
..........HHhhhhhhhhhHH.........
...........HHhhhhhhhHH..........
""",
    },
    "bun": {   # woman, hair up
        "down": """
............hhhhhhh.............
..........hhhhhhhhhhh...........
.........hhhhhhhhhhhhhh.........
.........hhhhhhhhhhhhhhh........
..........HhhhhhhhhhhhH.........
..........HhH.......HhH.........
..........HH.........HH.........
""",
        "side": """
............hhhhhhh.............
..........hhhhhhhhhhh...........
.........hhhhhhhhhhhhhhh........
.........hhhhhhhhhhhhhhhh.......
..........HhhhhhhhhhhhhhH.......
..........HH......HhhhhH........
...................HHH..........
""",
        "up": """
............hhhhhhh.............
..........hhhhhhhhhhh...........
.........hhhhhhhhhhhhhh.........
.........hhhhhhhhhhhhhhh........
..........hhhhhhhhhhhhh.........
..........HhhhhhhhhhhhH.........
..........HHhhhhhhhhhHH.........
...........HHhhhhhhhHH..........
""",
    },
}

# --- hats (k hat, K hat shadow, o outline) ---------------------------------
HATS = {
    "top": {
        "down": """
............kkkkkkkkk...........
...........kkkkkkkkkkk..........
...........kkkkkkkkkkk..........
...........kkkkkkkkkkk..........
...........KKKKKKKKKKK..........
........kkkkkkkkkkkkkkkkk.......
........KKKKKKKKKKKKKKKKK.......
""",
        "side": """
............kkkkkkkkkk..........
............kkkkkkkkkk..........
............kkkkkkkkkk..........
............kkkkkkkkkk..........
............KKKKKKKKKK..........
.........kkkkkkkkkkkkkkkk.......
.........KKKKKKKKKKKKKKKK.......
""",
        "up": """
............kkkkkkkkk...........
...........kkkkkkkkkkk..........
...........kkkkkkkkkkk..........
...........kkkkkkkkkkk..........
...........KKKKKKKKKKK..........
........kkkkkkkkkkkkkkkkk.......
........KKKKKKKKKKKKKKKKK.......
""",
    },
    "cap": {
        "down": """
................................
................................
............kkkkkkkk............
...........kkkkkkkkkk...........
..........kkkkkkkkkkkk..........
..........KKKKKKKKKKKK..........
""",
        "side": """
................................
................................
............kkkkkkkk............
...........kkkkkkkkkkk..........
..........kkkkkkkkkkkkkk........
..........KKKKKKKKKKKKKK........
""",
        "up": """
................................
................................
............kkkkkkkk............
...........kkkkkkkkkk...........
..........kkkkkkkkkkkk..........
..........KKKKKKKKKKKK..........
""",
    },
}

# --- faces: simple eye/brow marks per direction ---------------------------
FACE_DOWN = """
................................
................................
................................
................................
................................
................................
................................
................................
................................
............E......E............
...........oe.....oe............
................................
................................
..............m.m...............
...............mm...............
"""
FACE_SIDE = """
................................
................................
................................
................................
................................
................................
................................
................................
................................
..................E.............
..................oe............
................................
................................
...................m............
...................m............
"""

SKINS = {
    "pale": [(172, 122, 96), (236, 196, 166)],
    "ruddy": [(170, 108, 86), (232, 182, 150)],
    "olive": [(154, 110, 76), (222, 180, 138)],
    "grey": [(156, 124, 108), (220, 194, 176)],
    "brown": [(96, 62, 42), (150, 104, 72)],
}


def character(coat, skin="pale", hair="short", hair_col=(60, 44, 36), hat=None, hat_col=PAL["ink"],
              vest=None, trousers=None, shirt=PAL["white"], cravat=None, boots=PAL["ink"],
              eye=(24, 20, 22), dress=False):
    """Return dict of direction -> list of 4 frames (Canvas)."""
    skin_dark, skin_light = SKINS[skin]
    vest = vest or shade(coat, 0.8)
    trousers = trousers or shade(coat, 0.75)
    cravat = cravat or shirt
    key = {
        "o": PAL["ink"], "s": skin_light, "S": skin_dark,
        "c": coat, "C": shade(coat, 0.65), "l": shade(coat, 0.5),
        "w": shirt, "v": vest, "n": cravat,
        "p": trousers, "P": shade(trousers, 0.7),
        "b": boots, "B": shade(boots, 1.6),
        "h": hair_col, "H": shade(hair_col, 0.6),
        "k": hat_col, "K": shade(hat_col, 0.6),
        "E": shade(skin_dark, 0.7), "e": eye, "m": shade(skin_dark, 0.85),
    }
    out = {}
    for d in ["down", "side", "up"]:
        body = {"down": BODY_DOWN, "side": BODY_SIDE, "up": BODY_UP}[d]
        legs = {"down": LEGS_DOWN, "side": LEGS_SIDE, "up": LEGS_DOWN}[d]
        frames = []
        for leg in ["stand", "l", "stand", "r"]:
            c = Canvas(FW, FH)
            c.grid(body, key)
            # replace leg block (rows 35..46)
            c.rect(0, 35, FW, 12, (0, 0, 0, 0))
            if dress:
                # long skirt instead of legs
                for y in range(35, 46):
                    half = 5 + (y - 35) // 2
                    for x in range(16 - half, 16 + half + 1):
                        col = coat if (x + y) % 3 else shade(coat, 0.85)
                        if x in (16 - half, 16 + half):
                            col = PAL["ink"]
                        c.put(x, y, col)
                c.hline(16 - 10, 46, 21, PAL["ink"])
                if leg != "stand":
                    c.put(15 if leg == "l" else 17, 45, boots)
            else:
                c.grid(legs[leg], key, 0, 35)
            if d == "down":
                c.grid(FACE_DOWN, key)
            elif d == "side":
                c.grid(FACE_SIDE, key)
            if hair in HAIR:
                c.grid(HAIR[hair][d], key)
            if hat and hat in HATS:
                c.grid(HATS[hat][d], key)
            frames.append(c)
        out[d] = frames
    # left = flipped right
    out["left"] = [f.flip_h() for f in out["side"]]
    out["right"] = out.pop("side")
    return out


CHARACTERS = {
    # player: young clerk, brown coat, cap
    "player": dict(coat=(96, 70, 44), skin="pale", hair="short", hair_col=(84, 58, 36), vest=(150, 120, 70), trousers=(70, 60, 56)),
    "jackson": dict(coat=(30, 28, 34), skin="grey", hair="swept_up", hair_col=(236, 236, 232), vest=(44, 40, 48)),
    "calhoun": dict(coat=(26, 26, 30), skin="pale", hair="brushed_back", hair_col=(78, 72, 70)),
    "clay": dict(coat=(40, 32, 30), skin="ruddy", hair="receding", hair_col=(160, 152, 140), vest=(128, 98, 52)),
    "biddle": dict(coat=(34, 44, 66), skin="pale", hair="curly", hair_col=(58, 44, 36), vest=(206, 190, 150)),
    "ross": dict(coat=(52, 40, 32), skin="olive", hair="parted", hair_col=(44, 34, 30), vest=(80, 66, 48)),
    "gregory": dict(coat=(70, 58, 40), skin="pale", hair="thin_messy", hair_col=(150, 124, 78), vest=(96, 78, 50), shirt=(200, 190, 170)),
    "lawrence": dict(coat=(84, 70, 58), skin="grey", hair="wild", hair_col=(62, 50, 40), shirt=(170, 160, 140), vest=(84, 70, 58)),
    "magistrate": dict(coat=(36, 30, 28), skin="ruddy", hair="bald_whiskers", hair_col=(222, 218, 210), vest=(110, 40, 40)),
    # supporting cast
    "postmaster": dict(coat=(50, 60, 40), skin="ruddy", hair="short", hair_col=(120, 80, 40), vest=(180, 150, 80)),
    "jailer": dict(coat=(60, 56, 60), skin="ruddy", hair="short", hair_col=(60, 50, 40), hat="cap", hat_col=(50, 46, 50), vest=(60, 56, 60)),
    "tavernkeeper": dict(coat=(120, 110, 90), skin="ruddy", hair="bald_whiskers", hair_col=(120, 90, 60), shirt=(230, 220, 200), vest=(90, 60, 40)),
    "clerk": dict(coat=(60, 62, 80), skin="pale", hair="short", hair_col=(40, 34, 30), vest=(140, 130, 110)),
    "printer": dict(coat=(70, 70, 76), skin="pale", hair="short", hair_col=(90, 70, 50), shirt=(200, 200, 200), vest=(70, 70, 76)),
    "guard": dict(coat=(40, 52, 90), skin="olive", hair="short", hair_col=(30, 26, 24), hat="cap", hat_col=(40, 52, 90), vest=(200, 200, 200)),
    "delegate": dict(coat=(96, 60, 40), skin="olive", hair="short", hair_col=(30, 24, 22), vest=(180, 60, 50)),
    "gentleman": dict(coat=(30, 34, 40), skin="pale", hair="short", hair_col=(80, 60, 40), hat="top", vest=(180, 170, 140)),
    "gentleman2": dict(coat=(70, 40, 40), skin="ruddy", hair="receding", hair_col=(130, 120, 110), hat="top", vest=(120, 110, 80)),
    "lady": dict(coat=(90, 50, 80), skin="pale", hair="bun", hair_col=(90, 60, 40), dress=True),
    "lady2": dict(coat=(50, 70, 60), skin="ruddy", hair="bun", hair_col=(40, 30, 26), dress=True),
    "labourer": dict(coat=(110, 90, 60), skin="brown", hair="short", hair_col=(30, 24, 22), shirt=(200, 190, 170), hat="cap", hat_col=(90, 70, 50)),
    "boy": dict(coat=(80, 90, 110), skin="pale", hair="short", hair_col=(180, 140, 80), hat="cap", hat_col=(80, 60, 40)),
    "servant": dict(coat=(60, 60, 60), skin="brown", hair="short", hair_col=(20, 18, 18), shirt=(240, 240, 240), vest=(200, 200, 200)),
    "coachman": dict(coat=(50, 40, 60), skin="brown", hair="short", hair_col=(20, 18, 18), hat="top", hat_col=(40, 36, 40), vest=(150, 40, 40)),
}


def build_all():
    order = ["down", "left", "right", "up"]
    index = {}
    sheets = []
    for name, spec in CHARACTERS.items():
        frames = character(**spec)
        sheet = Canvas(FW * 4, FH * 4)
        for r, d in enumerate(order):
            for i, f in enumerate(frames[d]):
                sheet.blit(f, i * FW, r * FH)
        sheet.save(f"sprites/{name}.png")
        index[name] = {"fw": FW, "fh": FH, "rows": order, "frames": 4}
        sheets.append(sheet)
    with open(os.path.join(ASSETS, "sprites", "index.json"), "w") as f:
        json.dump(index, f)
    return sheets


if __name__ == "__main__":
    sheets = build_all()
    print(len(sheets), "characters")
    print(preview(sheets[:9], "sprites_a.png", scale=3))
    print(preview(sheets[9:], "sprites_b.png", scale=3))
